package com.example.appsvikavp;

import android.provider.ContactsContract;

import java.util.ArrayList;

public class FaunaData {
    public static String[][] data = new String[][]{
            {"Kucica ekor-kuning (Aceh)", "http://2.bp.blogspot.com/-JksNKFC3ZDk/UbxjnFhIceI/AAAAAAAAASQ/Gg2jKPmxyUs/w1200-h630-p-k-no-nu/Cempala+Kuneng+atau+Kucica+Ekor-kuning+(Trichixos+pyrropygus)+Maskot+(Fauna+Identitas)+Provinsi+Aceh.jpg", "Kucica ekor kuning adalah sebuah spesies burung dalam keluarga Muscicapidae. Burung ini dapat ditemukan di Brunei, Indonesia, Malaysia, dan Thailand. Habitat alaminya yaitu di hutan dataran rendah yang lembap dan rawa-rawa di daerah subtropis atau tropis. Burung ini merupakan fauna daerah Aceh yang dikenal dengan nama cémpala kunèng dalam bahasa Aceh. Saat ini burung ini berstatus hampir terancam."},
            {"Beo Nias (Sumatera Utara)", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Beo-2.jpg/280px-Beo-2.jpg", "Beo, mamiang, atau tiong emas (Gracula) adalah sejenis burung anggota suku Sturnidae (jalak dan kerabatnya). Wilayah persebaran alaminya adalah mulai dari Sri Lanka, India, Himalaya, ke timur hingga Filipina, jawa hingga kepulauan sunda kecil. Burung ini dapat ditemukan di dataran rendah hingga dataran tinggi lebih dari 2000m. Karena kemampuannya menirukan bahasa manusia, burung ini menjadi hewan peliharaan populer."},
            {"Kuau Raja (Sumatera Selatan)", "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/BxZ_Argusianus_argus_00x.jpg/225px-BxZ_Argusianus_argus_00x.jpg", "Kuau Raja atau dalam nama ilmiahnya Argusianus argus adalah salah satu burung yang terdapat di dalam suku Phasianidae. Kuau Raja mempunyai bulu berwarna coklat kemerahan dan kulit kepala berwarna biru. Burung jantan dewasa berukuran sangat besar, panjangnya dapat mencapai 200cm. Di atas kepalanya terdapat jambul dan bulu tengkuk berwarna kehitaman. Burung jantan dewasa juga memiliki bulu sayap dan ekor yang sangat panjang, dihiasi dengan bintik-bintik besar menyerupai mata serangga atau oceli. Burung betina berukuran lebih kecil dari burung jantan, panjangnya sekitar 75cm, dengan jambul kepala berwarna kecoklatan. Bulu ekor dan sayap betina tidak sepanjang burung jantan, dan hanya dihiasi dengan sedikit oceli."},
            {"Serindit (Riau)", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Stavenn_Loriculus_galgulus_00.jpg/225px-Stavenn_Loriculus_galgulus_00.jpg", "Serindit melayu atau dalam nama ilmiahnya Loriculus galgulus adalah sejenis burung yang terdapat di dalam genus burung serindit Loriculus. Burung ini berukuran kecil, dengan panjang mencapai 12cm. Bulunya didominasi oleh warna hijau dengan bulu ekor berwarna merah. Burung jantan dan betina serupa. Burung serindit jantan memiliki bercak kepala berwarna biru dan bercak tenggorokan berwarna merah. Burung betina berwarna lebih kusam dibanding jantan. Populasi Serindit melayu tersebar di hutan dataran rendah, dari permukaan laut sampai ketinggian 1,300m di negara Brunei, Indonesia, Malaysia, Singapura dan Thailand."},
            {"Ikan Kakap (Kepulauan Riau)", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Paddletail_melb_aquarium.jpg/320px-Paddletail_melb_aquarium.jpg", "Kakap adalah keluarga ikan laut dasaran yang hidup secara berkelompok di dasar-dasar karang atau terumbu karang. Mempunyai ciri tubuh yang bulat pipih dengan sirip memanjang sepanjang punggung. Jenis ikan kakap yang banyak ditemui di Indonesia adalah jenis kakap merah (L. campechanus). Beberapa jenis yang lain yang juga banyak ditemui adalah kakap kuning, kakap hitam dan lain-lain. \n" +
                    "Kakap merah merupakan fauna khas provinsi Kepulauan Riau dikarenakan provinsi ini merupakan tempat tinggal banyak kakap dan kakap sendiri sering dijadikan bahan makanan khas yaitu asam pedas"},
            {"Harimau Sumatera (Jambi)", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Sumatran_Tiger_Berlin_Tierpark.jpg/320px-Sumatran_Tiger_Berlin_Tierpark.jpg", "Harimau sumatra (bahasa Latin: Panthera tigris sumatrae) adalah subspesies harimau yang habitat aslinya di pulau Sumatra, dan merupakan satu dari enam subspesies harimau yang masih bertahan hidup hingga saat ini dan termasuk dalam klasifikasi satwa kritis yang terancam punah (critically endangered) dalam daftar merah spesies terancam yang dirilis Lembaga Konservasi Dunia IUCN. Populasi liar diperkirakan antara 400-500 ekor, terutama hidup di taman-taman nasional di Sumatra. Uji genetik mutakhir telah mengungkapkan tanda-tanda genetik yang unik, yang menandakan bahwa subspesies ini mungkin berkembang menjadi spesies terpisah, bila berhasil lestari."},
            {"Badak Jawa (Banten)", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Rhinoceros_sondaicus_in_London_Zoo.jpg/220px-Rhinoceros_sondaicus_in_London_Zoo.jpg", "Badak jawa, atau badak bercula-satu kecil (Rhinoceros sondaicus) adalah anggota famili Rhinocerotidae dan satu dari lima badak yang masih ada. Badak ini masih termasuk ke dalam genus yang sama dengan badak india dan memiliki kulit bermosaik yang menyerupai baju baja. Badak ini memiliki panjang 3,1–3,2 m dan tinggi 1,4–1,7 m. Badak ini lebih kecil daripada badak india dan lebih dekat dalam besar tubuh dengan badak hitam. Ukuran culanya biasanya lebih sedikit daripada 20 cm, lebih kecil daripada cula spesies badak lainnya"},
            {"Macan Tutul Jawa (Jawa Barat)", "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Panthera_pardus_melas_%28Tierpark_Berlin%29_-_1009-891-%28118%29.jpg/160px-Panthera_pardus_melas_%28Tierpark_Berlin%29_-_1009-891-%28118%29.jpg", "Macan tutul jawa (Panthera pardus melas) atau macan kumbang adalah salah satu subspesies dari macan tutul yang hanya ditemukan di hutan tropis, pegunungan dan kawasan konservasi Pulau Jawa, Indonesia. Macan tutul ini memiliki dua variasi warna kulit yaitu berwarna terang (oranye) dan hitam (macan kumbang). Macan tutul jawa adalah satwa indentitas Provinsi Jawa Barat."},
            {"Kepodang Emas (Jawa Tengah)", "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Black-naped_Oriole.jpg/320px-Black-naped_Oriole.jpg", "Kepudang kuduk-hitam (Oriolus chinensis) atau kepudang kapas adalah spesies burung dari keluarga Oriolidae, dari genus Oriolus. Burung ini memiliki habitat di hutan terbuka, hutan sekunder, hutan mangrove, perkebunan, pedesaan, tersebar sampai ketinggian 1.600 mdpl."},
            {"Jalak Bali (Bali)", "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Bali_Myna_in_Bali_Barat_National_Park.jpg/175px-Bali_Myna_in_Bali_Barat_National_Park.jpg", "Jalak Bali (Leucopsar rothschildi) adalah sejenis burung pengicau berukuran sedang, dengan panjang lebih kurang 25cm, dari suku Sturnidae. Ia turut dikenali sebagai Curik Ketimbang Jalak.. Jalak Bali hanya ditemukan di hutan bagian barat Pulau Bali dan merupakan hewan endemik Indonesia. Burung ini juga merupakan satu-satunya spesies endemik Bali dan pada tahun 1991 dinobatkan sebagai lambang fauna Provinsi Bali. "},
    };
    public static ArrayList<Fauna> getListData(){
        ArrayList<Fauna> list = new ArrayList<>();
        for (String[] aData : data){
            Fauna fauna = new Fauna();
            fauna.setName(aData[0]);
            fauna.setPhoto(aData[1]);
            fauna.setDescription(aData[2]);

            list.add(fauna);
        }
        return list;
    }
}